name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Force Clean and Override Kotlin Version
        run: |
          find . -type f \( -name "*.gradle" -o -name "*.kts" \) -exec sed -i 's/version "2.1.0"/version "1.9.24"/g' {} +
          find . -type f \( -name "*.gradle" -o -name "*.kts" \) -exec sed -i "s/version '2.1.0'/version '1.9.24'/g" {} +

      - name: Clean Flutter Project
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --no-pub

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
